Changing Orchestrator Outputs to Categorical
childmindresearch/wristpy pull request #128
Opened 2024-10-25 16:16 UTC by frey-perez

Description

2024-10-28 14:17 UTC, Asanto32 approved these changes
This also looks good to me, but my same comment from the other PR applies

2024-10-29 17:07 UTC, frey-perez commented
@ReinderVosDeWael this look good to merge ?

2024-10-29 17:09 UTC, ReinderVosDeWael requested changes
minor comment, so no need to ping me again, but I'd suggest using all lower-case names.

Remembering weeks down the line what you (did not) capitalize is a pain 😅

2024-10-29 17:28 UTC, ReinderVosDeWael approved these changes

2024-10-29 17:34 UTC, merged