Feat/issue 102/handle idle sleep mode
childmindresearch/wristpy pull request #143
Opened 2024-11-20 14:54 UTC by Asanto32

Support to handle the `idle_sleep_mode` for Actigraph watches. This function fills in time gaps in the data created by enabling `idle_sleep_mode`. In cases when the samples are not linearly spaced within one second, the data is resampled.

TODO:
- Add check in orchestrator/processing pipeline

2024-11-26 16:54 UTC, Asanto32 commented
This is ready for review now. Small chance of merge conflicts with the orchestrator compared to the new one with full directory processing but I tried to make sure it should work together.

Note: when there are significant amounts of `idle_sleep_mode` gaps it does slow down processing. Not due to the `idle_sleep_mode_imputation` (which only takes 5-10s), but from the addition of significantly more data points (example test case on my computer adds in more than 50% of the data thus increase in processing time by ~50%)

2024-11-27 15:40 UTC, ReinderVosDeWael approved these changes

2024-11-27 15:44 UTC, ReinderVosDeWael requested changes
Assess interaction with all locations where imputed data will be used e.g. calibration

2024-12-06 21:06 UTC, ReinderVosDeWael approved these changes

2024-12-09 15:38 UTC, merged